### ISSUE TITLE
Almost everything looks to be broken

### ISSUE THREAD

**Issue by Motzumoto** [Nekos-life/nekos.py#23]
Almost all endpoints are giving me this error except `spank`

```py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/LunarDev/AGB/Cogs/nsfw.py", line 401, in classic
    embed.set_image(url=nekos.img("classic"))
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nekos/nekos.py", line 43, in img
    return r["url"]
KeyError: 'url'
```

**Comment by Motzumoto** [comment]
![image](https://user-images.githubusercontent.com/45925152/166145689-b0689401-d40f-4e30-bb15-677a96e7524c.png)
![image](https://user-images.githubusercontent.com/45925152/166145693-793ccb59-526c-4198-b25a-289fc19c2167.png)


the endpoints are gone
