### ISSUE TITLE
This error?? No module named requests?

### ISSUE THREAD

**Issue by Yurismm** [Nekos-life/nekos.py#8]
Yui FunamiBOTToday at 21:46
Traceback (most recent call last):
  File "/app/cogs/developer.py", line 78, in _eval
    ret = await func()
  File "<string>", line 2, in func
  File "/app/.heroku/python/lib/python3.6/site-packages/nekos/__init__.py", line 4, in <module>
    from . import http
  File "/app/.heroku/python/lib/python3.6/site-packages/nekos/http.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by AlexFlipnote** [comment]
Do this command with sudo/Admin command prompt
```
pip install requests
```
